-- 初始資料：由 Excel 匯入，姓名已統一為「潘沅駿」

insert into public.swimmers(name,gender,school,grade,birth,note) values ('李亮樂','女','中正國中','9','2011/01/14','99尾~100頭') on conflict(name) do update set gender=excluded.gender,school=excluded.school,grade=excluded.grade,birth=excluded.birth,note=excluded.note;
insert into public.swimmers(name,gender,school,grade,birth,note) values ('曾子僑','女','重慶國中','8','2011/11/12','100尾~101頭') on conflict(name) do update set gender=excluded.gender,school=excluded.school,grade=excluded.grade,birth=excluded.birth,note=excluded.note;
insert into public.swimmers(name,gender,school,grade,birth,note) values ('潘沅駿','男','土城國中','8','2012/04/25',null) on conflict(name) do update set gender=excluded.gender,school=excluded.school,grade=excluded.grade,birth=excluded.birth,note=excluded.note;
insert into public.swimmers(name,gender,school,grade,birth,note) values ('彭奕凱','男','中山國小','7','2012/09/29','101尾~102頭') on conflict(name) do update set gender=excluded.gender,school=excluded.school,grade=excluded.grade,birth=excluded.birth,note=excluded.note;
insert into public.swimmers(name,gender,school,grade,birth,note) values ('劉昱成','男','板橋國小','7','2012/11/05',null) on conflict(name) do update set gender=excluded.gender,school=excluded.school,grade=excluded.grade,birth=excluded.birth,note=excluded.note;
insert into public.swimmers(name,gender,school,grade,birth,note) values ('胡庭瑞','男','中山國小','6','2014/05/12','102尾~103頭') on conflict(name) do update set gender=excluded.gender,school=excluded.school,grade=excluded.grade,birth=excluded.birth,note=excluded.note;
insert into public.swimmers(name,gender,school,grade,birth,note) values ('陳言安','男','埔墘國小','6','2014/05/14',null) on conflict(name) do update set gender=excluded.gender,school=excluded.school,grade=excluded.grade,birth=excluded.birth,note=excluded.note;
insert into public.swimmers(name,gender,school,grade,birth,note) values ('鍾昊恩','男','大觀國小','6','2014/05/17',null) on conflict(name) do update set gender=excluded.gender,school=excluded.school,grade=excluded.grade,birth=excluded.birth,note=excluded.note;
insert into public.swimmers(name,gender,school,grade,birth,note) values ('張境晏','女','中山國小','6','2014/06/23',null) on conflict(name) do update set gender=excluded.gender,school=excluded.school,grade=excluded.grade,birth=excluded.birth,note=excluded.note;
insert into public.swimmers(name,gender,school,grade,birth,note) values ('曾子瑞','男','中山國小','6','2014/07/16',null) on conflict(name) do update set gender=excluded.gender,school=excluded.school,grade=excluded.grade,birth=excluded.birth,note=excluded.note;
insert into public.swimmers(name,gender,school,grade,birth,note) values ('王柔伊','女','中山國小','5','2015/02/04','103尾~104頭') on conflict(name) do update set gender=excluded.gender,school=excluded.school,grade=excluded.grade,birth=excluded.birth,note=excluded.note;
insert into public.swimmers(name,gender,school,grade,birth,note) values ('陳衍均','男','大觀國小','5','2015/02/27',null) on conflict(name) do update set gender=excluded.gender,school=excluded.school,grade=excluded.grade,birth=excluded.birth,note=excluded.note;
insert into public.swimmers(name,gender,school,grade,birth,note) values ('姚家興','男','中山國小','5','2015/03/13',null) on conflict(name) do update set gender=excluded.gender,school=excluded.school,grade=excluded.grade,birth=excluded.birth,note=excluded.note;
insert into public.swimmers(name,gender,school,grade,birth,note) values ('尹亮允','女','中山國小','4','2015/09/29','104尾~105頭') on conflict(name) do update set gender=excluded.gender,school=excluded.school,grade=excluded.grade,birth=excluded.birth,note=excluded.note;
insert into public.swimmers(name,gender,school,grade,birth,note) values ('黃惟淵','男','莒光國小','4','2016/01/09',null) on conflict(name) do update set gender=excluded.gender,school=excluded.school,grade=excluded.grade,birth=excluded.birth,note=excluded.note;
insert into public.swimmers(name,gender,school,grade,birth,note) values ('潘昱晴','女','廣福國小','4','2016/01/17',null) on conflict(name) do update set gender=excluded.gender,school=excluded.school,grade=excluded.grade,birth=excluded.birth,note=excluded.note;
insert into public.swimmers(name,gender,school,grade,birth,note) values ('廖書汎','男','中山國小','4','2016/07/11',null) on conflict(name) do update set gender=excluded.gender,school=excluded.school,grade=excluded.grade,birth=excluded.birth,note=excluded.note;
insert into public.swimmers(name,gender,school,grade,birth,note) values ('唐紫芯','女','裕德國際學校','4','2016/08/08',null) on conflict(name) do update set gender=excluded.gender,school=excluded.school,grade=excluded.grade,birth=excluded.birth,note=excluded.note;
insert into public.swimmers(name,gender,school,grade,birth,note) values ('翁晨軒','男','大觀國小','3','2017/01/22','105尾~106頭') on conflict(name) do update set gender=excluded.gender,school=excluded.school,grade=excluded.grade,birth=excluded.birth,note=excluded.note;
insert into public.swimmers(name,gender,school,grade,birth,note) values ('楊鎧銓','男','康橋國際學校','3','2017/03/08',null) on conflict(name) do update set gender=excluded.gender,school=excluded.school,grade=excluded.grade,birth=excluded.birth,note=excluded.note;
insert into public.swimmers(name,gender,school,grade,birth,note) values ('高珩晉','男','康橋國際學校','3','2017/08/21',null) on conflict(name) do update set gender=excluded.gender,school=excluded.school,grade=excluded.grade,birth=excluded.birth,note=excluded.note;
insert into public.swimmers(name,gender,school,grade,birth,note) values ('王暐蘅','男','中山國小','2','2017/09/25','106尾~107頭') on conflict(name) do update set gender=excluded.gender,school=excluded.school,grade=excluded.grade,birth=excluded.birth,note=excluded.note;
insert into public.swimmers(name,gender,school,grade,birth,note) values ('張可勻','男','土城國小','2','2018/06/21',null) on conflict(name) do update set gender=excluded.gender,school=excluded.school,grade=excluded.grade,birth=excluded.birth,note=excluded.note;
insert into public.swimmers(name,gender,school,grade,birth,note) values ('高赫言','男','康橋國際學校','1','2018/11/13','107尾~108頭') on conflict(name) do update set gender=excluded.gender,school=excluded.school,grade=excluded.grade,birth=excluded.birth,note=excluded.note;
insert into public.swimmers(name,gender,school,grade,birth,note) values ('陳廷峰','男','大觀國中','9','2010/12/26',null) on conflict(name) do update set gender=excluded.gender,school=excluded.school,grade=excluded.grade,birth=excluded.birth,note=excluded.note;
insert into public.swimmers(name,gender,school,grade,birth,note) values ('簡歆宸','女','大觀國小','5','2015/05/18',null) on conflict(name) do update set gender=excluded.gender,school=excluded.school,grade=excluded.grade,birth=excluded.birth,note=excluded.note;
insert into public.swimmers(name,gender,school,grade,birth,note) values ('簡歆芸','女','大觀國小','2','2018/05/06',null) on conflict(name) do update set gender=excluded.gender,school=excluded.school,grade=excluded.grade,birth=excluded.birth,note=excluded.note;
insert into public.swimmers(name,gender,school,grade,birth,note) values ('鄧丞勛','男','大觀國小','2','2018/07/17',null) on conflict(name) do update set gender=excluded.gender,school=excluded.school,grade=excluded.grade,birth=excluded.birth,note=excluded.note;
insert into public.swimmers(name,gender,school,grade,birth,note) values ('梁義謹','男','大觀國中','9','2011/01/15',null) on conflict(name) do update set gender=excluded.gender,school=excluded.school,grade=excluded.grade,birth=excluded.birth,note=excluded.note;
insert into public.swimmers(name,gender,school,grade,birth,note) values ('吳秉曄','男','實踐國小','6','2013/12/23',null) on conflict(name) do update set gender=excluded.gender,school=excluded.school,grade=excluded.grade,birth=excluded.birth,note=excluded.note;
insert into public.swimmers(name,gender,school,grade,birth,note) values ('王欣蔓','女','中山國小','6',null,null) on conflict(name) do update set gender=excluded.gender,school=excluded.school,grade=excluded.grade,birth=excluded.birth,note=excluded.note;
insert into public.swimmers(name,gender,school,grade,birth,note) values ('邱苡甯','女',null,'4',null,null) on conflict(name) do update set gender=excluded.gender,school=excluded.school,grade=excluded.grade,birth=excluded.birth,note=excluded.note;
insert into public.swimmers(name,gender,school,grade,birth,note) values ('邱莛玹','女',null,'4',null,null) on conflict(name) do update set gender=excluded.gender,school=excluded.school,grade=excluded.grade,birth=excluded.birth,note=excluded.note;
insert into public.swimmers(name,gender,school,grade,birth,note) values ('林祉妡',null,null,'4',null,null) on conflict(name) do update set gender=excluded.gender,school=excluded.school,grade=excluded.grade,birth=excluded.birth,note=excluded.note;
insert into public.swimmers(name,gender,school,grade,birth,note) values ('張可言','男','土城國中','7','2013/01/31',null) on conflict(name) do update set gender=excluded.gender,school=excluded.school,grade=excluded.grade,birth=excluded.birth,note=excluded.note;
insert into public.swimmers(name,gender,school,grade,birth,note) values ('翁唯軒','男','恆毅中學','9','2010/11/04',null) on conflict(name) do update set gender=excluded.gender,school=excluded.school,grade=excluded.grade,birth=excluded.birth,note=excluded.note;
insert into public.swimmers(name,gender,school,grade,birth,note) values ('池永璋','男','大觀國中','8','2012/06/01',null) on conflict(name) do update set gender=excluded.gender,school=excluded.school,grade=excluded.grade,birth=excluded.birth,note=excluded.note;
insert into public.swimmers(name,gender,school,grade,birth,note) values ('洪瑀彤','女','中山國小','7','2012/10/10',null) on conflict(name) do update set gender=excluded.gender,school=excluded.school,grade=excluded.grade,birth=excluded.birth,note=excluded.note;
insert into public.swimmers(name,gender,school,grade,birth,note) values ('王霈晴','女','中山國小','7','2012/10/12',null) on conflict(name) do update set gender=excluded.gender,school=excluded.school,grade=excluded.grade,birth=excluded.birth,note=excluded.note;
insert into public.swimmers(name,gender,school,grade,birth,note) values ('高語均','女','中山國小','7','2013/02/11',null) on conflict(name) do update set gender=excluded.gender,school=excluded.school,grade=excluded.grade,birth=excluded.birth,note=excluded.note;
insert into public.swimmers(name,gender,school,grade,birth,note) values ('鄧宇勝','男','大觀國小','7','2013/05/08',null) on conflict(name) do update set gender=excluded.gender,school=excluded.school,grade=excluded.grade,birth=excluded.birth,note=excluded.note;
insert into public.swimmers(name,gender,school,grade,birth,note) values ('李瑨宸','男','福瑞斯特高級中學','4','2015/11/24',null) on conflict(name) do update set gender=excluded.gender,school=excluded.school,grade=excluded.grade,birth=excluded.birth,note=excluded.note;
insert into public.swimmers(name,gender,school,grade,birth,note) values ('古羽立','男','康橋國際學校','3','2016/11/29',null) on conflict(name) do update set gender=excluded.gender,school=excluded.school,grade=excluded.grade,birth=excluded.birth,note=excluded.note;
insert into public.performances(swimmer_id,swimmer_name,course,event,seconds) select id,name,'長池','50自',31.33 from public.swimmers where name='李亮樂';
insert into public.performances(swimmer_id,swimmer_name,course,event,seconds) select id,name,'長池','50仰',38.51 from public.swimmers where name='李亮樂';
insert into public.performances(swimmer_id,swimmer_name,course,event,seconds) select id,name,'長池','50蛙',45.08 from public.swimmers where name='李亮樂';
insert into public.performances(swimmer_id,swimmer_name,course,event,seconds) select id,name,'長池','50蝶',33.55 from public.swimmers where name='李亮樂';
insert into public.performances(swimmer_id,swimmer_name,course,event,seconds) select id,name,'長池','100自',69.81 from public.swimmers where name='李亮樂';
insert into public.performances(swimmer_id,swimmer_name,course,event,seconds) select id,name,'長池','100仰',90.85 from public.swimmers where name='李亮樂';
insert into public.performances(swimmer_id,swimmer_name,course,event,seconds) select id,name,'長池','100蝶',87.32 from public.swimmers where name='李亮樂';
insert into public.performances(swimmer_id,swimmer_name,course,event,seconds) select id,name,'長池','50自',29.38 from public.swimmers where name='潘沅駿';
insert into public.performances(swimmer_id,swimmer_name,course,event,seconds) select id,name,'長池','50仰',34.19 from public.swimmers where name='潘沅駿';
insert into public.performances(swimmer_id,swimmer_name,course,event,seconds) select id,name,'長池','50蛙',33.29 from public.swimmers where name='潘沅駿';
insert into public.performances(swimmer_id,swimmer_name,course,event,seconds) select id,name,'長池','50蝶',32.47 from public.swimmers where name='潘沅駿';
insert into public.performances(swimmer_id,swimmer_name,course,event,seconds) select id,name,'長池','100自',63.74 from public.swimmers where name='潘沅駿';
insert into public.performances(swimmer_id,swimmer_name,course,event,seconds) select id,name,'長池','100仰',73.78 from public.swimmers where name='潘沅駿';
insert into public.performances(swimmer_id,swimmer_name,course,event,seconds) select id,name,'長池','100蛙',72.51 from public.swimmers where name='潘沅駿';
insert into public.performances(swimmer_id,swimmer_name,course,event,seconds) select id,name,'長池','100蝶',70.77 from public.swimmers where name='潘沅駿';
insert into public.performances(swimmer_id,swimmer_name,course,event,seconds) select id,name,'長池','200自',141.69 from public.swimmers where name='潘沅駿';
insert into public.performances(swimmer_id,swimmer_name,course,event,seconds) select id,name,'長池','200混',152.03 from public.swimmers where name='潘沅駿';
insert into public.performances(swimmer_id,swimmer_name,course,event,seconds) select id,name,'長池','200蛙',159.47 from public.swimmers where name='潘沅駿';
insert into public.performances(swimmer_id,swimmer_name,course,event,seconds) select id,name,'長池','50自',31.34 from public.swimmers where name='彭奕凱';
insert into public.performances(swimmer_id,swimmer_name,course,event,seconds) select id,name,'長池','50仰',38.44 from public.swimmers where name='彭奕凱';
insert into public.performances(swimmer_id,swimmer_name,course,event,seconds) select id,name,'長池','50蛙',40.32 from public.swimmers where name='彭奕凱';
insert into public.performances(swimmer_id,swimmer_name,course,event,seconds) select id,name,'長池','50蝶',35.39 from public.swimmers where name='彭奕凱';
insert into public.performances(swimmer_id,swimmer_name,course,event,seconds) select id,name,'長池','100自',67.92 from public.swimmers where name='彭奕凱';
insert into public.performances(swimmer_id,swimmer_name,course,event,seconds) select id,name,'長池','100蛙',86.38 from public.swimmers where name='彭奕凱';
insert into public.performances(swimmer_id,swimmer_name,course,event,seconds) select id,name,'長池','200自',150.99 from public.swimmers where name='彭奕凱';
insert into public.performances(swimmer_id,swimmer_name,course,event,seconds) select id,name,'長池','200混',168.71 from public.swimmers where name='彭奕凱';
insert into public.performances(swimmer_id,swimmer_name,course,event,seconds) select id,name,'長池','50自',32.09 from public.swimmers where name='曾子瑞';
insert into public.performances(swimmer_id,swimmer_name,course,event,seconds) select id,name,'長池','50仰',36.88 from public.swimmers where name='曾子瑞';
insert into public.performances(swimmer_id,swimmer_name,course,event,seconds) select id,name,'長池','50蛙',40.48 from public.swimmers where name='曾子瑞';
insert into public.performances(swimmer_id,swimmer_name,course,event,seconds) select id,name,'長池','50蝶',35.09 from public.swimmers where name='曾子瑞';
insert into public.performances(swimmer_id,swimmer_name,course,event,seconds) select id,name,'長池','100自',69.87 from public.swimmers where name='曾子瑞';
insert into public.performances(swimmer_id,swimmer_name,course,event,seconds) select id,name,'長池','100仰',78.34 from public.swimmers where name='曾子瑞';
insert into public.performances(swimmer_id,swimmer_name,course,event,seconds) select id,name,'長池','100蛙',88.48 from public.swimmers where name='曾子瑞';
insert into public.performances(swimmer_id,swimmer_name,course,event,seconds) select id,name,'長池','100蝶',79.65 from public.swimmers where name='曾子瑞';
insert into public.performances(swimmer_id,swimmer_name,course,event,seconds) select id,name,'長池','200自',148.62 from public.swimmers where name='曾子瑞';
insert into public.performances(swimmer_id,swimmer_name,course,event,seconds) select id,name,'長池','200混',166.76 from public.swimmers where name='曾子瑞';
insert into public.performances(swimmer_id,swimmer_name,course,event,seconds) select id,name,'長池','400自',315.93 from public.swimmers where name='曾子瑞';
insert into public.performances(swimmer_id,swimmer_name,course,event,seconds) select id,name,'長池','50自',34.35 from public.swimmers where name='陳言安';
insert into public.performances(swimmer_id,swimmer_name,course,event,seconds) select id,name,'長池','50蛙',45.21 from public.swimmers where name='陳言安';
insert into public.performances(swimmer_id,swimmer_name,course,event,seconds) select id,name,'長池','50蝶',37.05 from public.swimmers where name='陳言安';
insert into public.performances(swimmer_id,swimmer_name,course,event,seconds) select id,name,'長池','100自',75.38 from public.swimmers where name='陳言安';
insert into public.performances(swimmer_id,swimmer_name,course,event,seconds) select id,name,'長池','200自',169.38 from public.swimmers where name='陳言安';
insert into public.performances(swimmer_id,swimmer_name,course,event,seconds) select id,name,'長池','200混',178.9 from public.swimmers where name='陳言安';
insert into public.performances(swimmer_id,swimmer_name,course,event,seconds) select id,name,'長池','50自',36.53 from public.swimmers where name='張境晏';
insert into public.performances(swimmer_id,swimmer_name,course,event,seconds) select id,name,'長池','50仰',41.7 from public.swimmers where name='張境晏';
insert into public.performances(swimmer_id,swimmer_name,course,event,seconds) select id,name,'長池','50蛙',49.94 from public.swimmers where name='張境晏';
insert into public.performances(swimmer_id,swimmer_name,course,event,seconds) select id,name,'長池','50蝶',39.49 from public.swimmers where name='張境晏';
insert into public.performances(swimmer_id,swimmer_name,course,event,seconds) select id,name,'長池','100自',78.78 from public.swimmers where name='張境晏';
insert into public.performances(swimmer_id,swimmer_name,course,event,seconds) select id,name,'長池','200自',178.37 from public.swimmers where name='張境晏';
insert into public.performances(swimmer_id,swimmer_name,course,event,seconds) select id,name,'長池','200混',196.52 from public.swimmers where name='張境晏';
insert into public.performances(swimmer_id,swimmer_name,course,event,seconds) select id,name,'長池','50自',36.22 from public.swimmers where name='王柔伊';
insert into public.performances(swimmer_id,swimmer_name,course,event,seconds) select id,name,'長池','50仰',41.65 from public.swimmers where name='王柔伊';
insert into public.performances(swimmer_id,swimmer_name,course,event,seconds) select id,name,'長池','50蛙',47.48 from public.swimmers where name='王柔伊';
insert into public.performances(swimmer_id,swimmer_name,course,event,seconds) select id,name,'長池','50蝶',38.62 from public.swimmers where name='王柔伊';
insert into public.performances(swimmer_id,swimmer_name,course,event,seconds) select id,name,'長池','100自',77.45 from public.swimmers where name='王柔伊';
insert into public.performances(swimmer_id,swimmer_name,course,event,seconds) select id,name,'長池','100仰',86.5 from public.swimmers where name='王柔伊';
insert into public.performances(swimmer_id,swimmer_name,course,event,seconds) select id,name,'長池','100蛙',103.33 from public.swimmers where name='王柔伊';
insert into public.performances(swimmer_id,swimmer_name,course,event,seconds) select id,name,'長池','100蝶',89.17 from public.swimmers where name='王柔伊';
insert into public.performances(swimmer_id,swimmer_name,course,event,seconds) select id,name,'長池','200自',171.66 from public.swimmers where name='王柔伊';
insert into public.performances(swimmer_id,swimmer_name,course,event,seconds) select id,name,'長池','200混',187.07 from public.swimmers where name='王柔伊';
insert into public.performances(swimmer_id,swimmer_name,course,event,seconds) select id,name,'長池','50自',34.29 from public.swimmers where name='姚家興';
insert into public.performances(swimmer_id,swimmer_name,course,event,seconds) select id,name,'長池','50仰',41.23 from public.swimmers where name='姚家興';
insert into public.performances(swimmer_id,swimmer_name,course,event,seconds) select id,name,'長池','50蛙',43.31 from public.swimmers where name='姚家興';
insert into public.performances(swimmer_id,swimmer_name,course,event,seconds) select id,name,'長池','50蝶',39.46 from public.swimmers where name='姚家興';
insert into public.performances(swimmer_id,swimmer_name,course,event,seconds) select id,name,'長池','100自',74.44 from public.swimmers where name='姚家興';
insert into public.performances(swimmer_id,swimmer_name,course,event,seconds) select id,name,'長池','100仰',86.82 from public.swimmers where name='姚家興';
insert into public.performances(swimmer_id,swimmer_name,course,event,seconds) select id,name,'長池','100蛙',95.74 from public.swimmers where name='姚家興';
insert into public.performances(swimmer_id,swimmer_name,course,event,seconds) select id,name,'長池','100蝶',88.55 from public.swimmers where name='姚家興';
insert into public.performances(swimmer_id,swimmer_name,course,event,seconds) select id,name,'長池','200自',167.04 from public.swimmers where name='姚家興';
insert into public.performances(swimmer_id,swimmer_name,course,event,seconds) select id,name,'長池','200混',178.19 from public.swimmers where name='姚家興';
insert into public.performances(swimmer_id,swimmer_name,course,event,seconds) select id,name,'長池','50自',32.8 from public.swimmers where name='潘昱晴';
insert into public.performances(swimmer_id,swimmer_name,course,event,seconds) select id,name,'長池','50仰',38.05 from public.swimmers where name='潘昱晴';
insert into public.performances(swimmer_id,swimmer_name,course,event,seconds) select id,name,'長池','50蛙',43.49 from public.swimmers where name='潘昱晴';
insert into public.performances(swimmer_id,swimmer_name,course,event,seconds) select id,name,'長池','50蝶',35.78 from public.swimmers where name='潘昱晴';
insert into public.performances(swimmer_id,swimmer_name,course,event,seconds) select id,name,'長池','100自',69.85 from public.swimmers where name='潘昱晴';
insert into public.performances(swimmer_id,swimmer_name,course,event,seconds) select id,name,'長池','100仰',80.38 from public.swimmers where name='潘昱晴';
insert into public.performances(swimmer_id,swimmer_name,course,event,seconds) select id,name,'長池','100蛙',90.44 from public.swimmers where name='潘昱晴';
insert into public.performances(swimmer_id,swimmer_name,course,event,seconds) select id,name,'長池','100蝶',80.65 from public.swimmers where name='潘昱晴';
insert into public.performances(swimmer_id,swimmer_name,course,event,seconds) select id,name,'長池','200自',148.72 from public.swimmers where name='潘昱晴';
insert into public.performances(swimmer_id,swimmer_name,course,event,seconds) select id,name,'長池','200混',167.44 from public.swimmers where name='潘昱晴';
insert into public.performances(swimmer_id,swimmer_name,course,event,seconds) select id,name,'長池','50自',33.98 from public.swimmers where name='尹亮允';
insert into public.performances(swimmer_id,swimmer_name,course,event,seconds) select id,name,'長池','50仰',39.69 from public.swimmers where name='尹亮允';
insert into public.performances(swimmer_id,swimmer_name,course,event,seconds) select id,name,'長池','50蛙',41.84 from public.swimmers where name='尹亮允';
insert into public.performances(swimmer_id,swimmer_name,course,event,seconds) select id,name,'長池','50蝶',37.23 from public.swimmers where name='尹亮允';
insert into public.performances(swimmer_id,swimmer_name,course,event,seconds) select id,name,'長池','100自',72.04 from public.swimmers where name='尹亮允';
insert into public.performances(swimmer_id,swimmer_name,course,event,seconds) select id,name,'長池','100仰',83.13 from public.swimmers where name='尹亮允';
insert into public.performances(swimmer_id,swimmer_name,course,event,seconds) select id,name,'長池','100蛙',88.69 from public.swimmers where name='尹亮允';
insert into public.performances(swimmer_id,swimmer_name,course,event,seconds) select id,name,'長池','100蝶',86.42 from public.swimmers where name='尹亮允';
insert into public.performances(swimmer_id,swimmer_name,course,event,seconds) select id,name,'長池','200自',153.14 from public.swimmers where name='尹亮允';
insert into public.performances(swimmer_id,swimmer_name,course,event,seconds) select id,name,'長池','200混',168.42 from public.swimmers where name='尹亮允';
insert into public.performances(swimmer_id,swimmer_name,course,event,seconds) select id,name,'長池','200蛙',188.11 from public.swimmers where name='尹亮允';
insert into public.performances(swimmer_id,swimmer_name,course,event,seconds) select id,name,'長池','400自',324.6 from public.swimmers where name='尹亮允';
insert into public.performances(swimmer_id,swimmer_name,course,event,seconds) select id,name,'長池','50自',38.1 from public.swimmers where name='楊鎧銓';
insert into public.performances(swimmer_id,swimmer_name,course,event,seconds) select id,name,'長池','50仰',41.76 from public.swimmers where name='楊鎧銓';
insert into public.performances(swimmer_id,swimmer_name,course,event,seconds) select id,name,'長池','50蛙',50.68 from public.swimmers where name='楊鎧銓';
insert into public.performances(swimmer_id,swimmer_name,course,event,seconds) select id,name,'長池','50蝶',38.36 from public.swimmers where name='楊鎧銓';
insert into public.performances(swimmer_id,swimmer_name,course,event,seconds) select id,name,'長池','100自',79.5 from public.swimmers where name='楊鎧銓';
insert into public.performances(swimmer_id,swimmer_name,course,event,seconds) select id,name,'長池','100仰',90.78 from public.swimmers where name='楊鎧銓';
insert into public.performances(swimmer_id,swimmer_name,course,event,seconds) select id,name,'長池','100蛙',109.64 from public.swimmers where name='楊鎧銓';
insert into public.performances(swimmer_id,swimmer_name,course,event,seconds) select id,name,'長池','100蝶',82.57 from public.swimmers where name='楊鎧銓';
insert into public.performances(swimmer_id,swimmer_name,course,event,seconds) select id,name,'長池','200自',174.04 from public.swimmers where name='楊鎧銓';
insert into public.performances(swimmer_id,swimmer_name,course,event,seconds) select id,name,'長池','200混',187.0 from public.swimmers where name='楊鎧銓';
insert into public.performances(swimmer_id,swimmer_name,course,event,seconds) select id,name,'長池','50自',38.7 from public.swimmers where name='高珩晉';
insert into public.performances(swimmer_id,swimmer_name,course,event,seconds) select id,name,'長池','50仰',45.94 from public.swimmers where name='高珩晉';
insert into public.performances(swimmer_id,swimmer_name,course,event,seconds) select id,name,'長池','50蛙',53.17 from public.swimmers where name='高珩晉';
insert into public.performances(swimmer_id,swimmer_name,course,event,seconds) select id,name,'長池','50蝶',49.02 from public.swimmers where name='高珩晉';
insert into public.performances(swimmer_id,swimmer_name,course,event,seconds) select id,name,'長池','100自',84.19 from public.swimmers where name='高珩晉';
insert into public.performances(swimmer_id,swimmer_name,course,event,seconds) select id,name,'長池','50自',37.05 from public.swimmers where name='王暐蘅';
insert into public.performances(swimmer_id,swimmer_name,course,event,seconds) select id,name,'長池','50仰',43.57 from public.swimmers where name='王暐蘅';
insert into public.performances(swimmer_id,swimmer_name,course,event,seconds) select id,name,'長池','50蛙',47.97 from public.swimmers where name='王暐蘅';
insert into public.performances(swimmer_id,swimmer_name,course,event,seconds) select id,name,'長池','50蝶',40.31 from public.swimmers where name='王暐蘅';
insert into public.performances(swimmer_id,swimmer_name,course,event,seconds) select id,name,'長池','100自',79.12 from public.swimmers where name='王暐蘅';
insert into public.performances(swimmer_id,swimmer_name,course,event,seconds) select id,name,'長池','100仰',93.0 from public.swimmers where name='王暐蘅';
insert into public.performances(swimmer_id,swimmer_name,course,event,seconds) select id,name,'長池','100蛙',101.3 from public.swimmers where name='王暐蘅';
insert into public.performances(swimmer_id,swimmer_name,course,event,seconds) select id,name,'長池','100蝶',84.14 from public.swimmers where name='王暐蘅';
insert into public.performances(swimmer_id,swimmer_name,course,event,seconds) select id,name,'長池','200自',171.55 from public.swimmers where name='王暐蘅';
insert into public.performances(swimmer_id,swimmer_name,course,event,seconds) select id,name,'長池','200混',186.91 from public.swimmers where name='王暐蘅';
insert into public.performances(swimmer_id,swimmer_name,course,event,seconds) select id,name,'長池','50自',37.07 from public.swimmers where name='鄧丞勛';
insert into public.performances(swimmer_id,swimmer_name,course,event,seconds) select id,name,'長池','50仰',44.05 from public.swimmers where name='鄧丞勛';
insert into public.performances(swimmer_id,swimmer_name,course,event,seconds) select id,name,'長池','50蛙',45.85 from public.swimmers where name='鄧丞勛';
insert into public.performances(swimmer_id,swimmer_name,course,event,seconds) select id,name,'長池','50蝶',41.29 from public.swimmers where name='鄧丞勛';
insert into public.performances(swimmer_id,swimmer_name,course,event,seconds) select id,name,'長池','100自',81.23 from public.swimmers where name='鄧丞勛';
insert into public.performances(swimmer_id,swimmer_name,course,event,seconds) select id,name,'長池','100仰',94.42 from public.swimmers where name='鄧丞勛';
insert into public.performances(swimmer_id,swimmer_name,course,event,seconds) select id,name,'長池','100蛙',101.39 from public.swimmers where name='鄧丞勛';
insert into public.performances(swimmer_id,swimmer_name,course,event,seconds) select id,name,'長池','200自',178.1 from public.swimmers where name='鄧丞勛';
insert into public.performances(swimmer_id,swimmer_name,course,event,seconds) select id,name,'長池','200混',187.92 from public.swimmers where name='鄧丞勛';
insert into public.performances(swimmer_id,swimmer_name,course,event,seconds) select id,name,'長池','50自',39.53 from public.swimmers where name='高赫言';
insert into public.performances(swimmer_id,swimmer_name,course,event,seconds) select id,name,'長池','50仰',46.81 from public.swimmers where name='高赫言';
insert into public.performances(swimmer_id,swimmer_name,course,event,seconds) select id,name,'長池','50蛙',55.1 from public.swimmers where name='高赫言';
insert into public.performances(swimmer_id,swimmer_name,course,event,seconds) select id,name,'長池','50蝶',47.2 from public.swimmers where name='高赫言';
insert into public.performances(swimmer_id,swimmer_name,course,event,seconds) select id,name,'長池','100自',99.64 from public.swimmers where name='高赫言';
insert into public.performances(swimmer_id,swimmer_name,course,event,seconds) select id,name,'長池','50自',31.33 from public.swimmers where name='隊史女';
insert into public.performances(swimmer_id,swimmer_name,course,event,seconds) select id,name,'長池','50仰',36.87 from public.swimmers where name='隊史女';
insert into public.performances(swimmer_id,swimmer_name,course,event,seconds) select id,name,'長池','50蛙',41.84 from public.swimmers where name='隊史女';
insert into public.performances(swimmer_id,swimmer_name,course,event,seconds) select id,name,'長池','50蝶',33.55 from public.swimmers where name='隊史女';
insert into public.performances(swimmer_id,swimmer_name,course,event,seconds) select id,name,'長池','100自',69.81 from public.swimmers where name='隊史女';
insert into public.performances(swimmer_id,swimmer_name,course,event,seconds) select id,name,'長池','100仰',79.86 from public.swimmers where name='隊史女';
insert into public.performances(swimmer_id,swimmer_name,course,event,seconds) select id,name,'長池','100蛙',88.69 from public.swimmers where name='隊史女';
insert into public.performances(swimmer_id,swimmer_name,course,event,seconds) select id,name,'長池','100蝶',80.65 from public.swimmers where name='隊史女';
insert into public.performances(swimmer_id,swimmer_name,course,event,seconds) select id,name,'長池','200自',148.72 from public.swimmers where name='隊史女';
insert into public.performances(swimmer_id,swimmer_name,course,event,seconds) select id,name,'長池','200混',167.44 from public.swimmers where name='隊史女';
insert into public.performances(swimmer_id,swimmer_name,course,event,seconds) select id,name,'長池','200蛙',188.11 from public.swimmers where name='隊史女';
insert into public.performances(swimmer_id,swimmer_name,course,event,seconds) select id,name,'長池','400自',315.93 from public.swimmers where name='隊史女';
insert into public.performances(swimmer_id,swimmer_name,course,event,seconds) select id,name,'長池','50自',29.38 from public.swimmers where name='隊史男';
insert into public.performances(swimmer_id,swimmer_name,course,event,seconds) select id,name,'長池','50仰',34.19 from public.swimmers where name='隊史男';
insert into public.performances(swimmer_id,swimmer_name,course,event,seconds) select id,name,'長池','50蛙',33.29 from public.swimmers where name='隊史男';
insert into public.performances(swimmer_id,swimmer_name,course,event,seconds) select id,name,'長池','50蝶',32.47 from public.swimmers where name='隊史男';
insert into public.performances(swimmer_id,swimmer_name,course,event,seconds) select id,name,'長池','100自',63.74 from public.swimmers where name='隊史男';
insert into public.performances(swimmer_id,swimmer_name,course,event,seconds) select id,name,'長池','100仰',73.78 from public.swimmers where name='隊史男';
insert into public.performances(swimmer_id,swimmer_name,course,event,seconds) select id,name,'長池','100蛙',72.51 from public.swimmers where name='隊史男';
insert into public.performances(swimmer_id,swimmer_name,course,event,seconds) select id,name,'長池','100蝶',70.77 from public.swimmers where name='隊史男';
insert into public.performances(swimmer_id,swimmer_name,course,event,seconds) select id,name,'長池','200自',141.69 from public.swimmers where name='隊史男';
insert into public.performances(swimmer_id,swimmer_name,course,event,seconds) select id,name,'長池','200混',152.03 from public.swimmers where name='隊史男';
insert into public.performances(swimmer_id,swimmer_name,course,event,seconds) select id,name,'長池','200蛙',159.47 from public.swimmers where name='隊史男';
insert into public.performances(swimmer_id,swimmer_name,course,event,seconds) select id,name,'長池','400自',324.6 from public.swimmers where name='隊史男';
insert into public.performances(swimmer_id,swimmer_name,course,event,seconds) select id,name,'短池','50蝶',35.72 from public.swimmers where name='曾子瑞';
insert into public.performances(swimmer_id,swimmer_name,course,event,seconds) select id,name,'短池','100仰',78.08 from public.swimmers where name='曾子瑞';
insert into public.performances(swimmer_id,swimmer_name,course,event,seconds) select id,name,'短池','100混',78.81 from public.swimmers where name='曾子瑞';
insert into public.performances(swimmer_id,swimmer_name,course,event,seconds) select id,name,'短池','50自',38.44 from public.swimmers where name='王柔伊';
insert into public.performances(swimmer_id,swimmer_name,course,event,seconds) select id,name,'短池','100混',101.33 from public.swimmers where name='王柔伊';
insert into public.performances(swimmer_id,swimmer_name,course,event,seconds) select id,name,'短池','50蝶',42.43 from public.swimmers where name='姚家興';
insert into public.performances(swimmer_id,swimmer_name,course,event,seconds) select id,name,'短池','100自',78.9 from public.swimmers where name='姚家興';
insert into public.performances(swimmer_id,swimmer_name,course,event,seconds) select id,name,'短池','100混',88.59 from public.swimmers where name='姚家興';
insert into public.performances(swimmer_id,swimmer_name,course,event,seconds) select id,name,'短池','50蛙',45.23 from public.swimmers where name='尹亮允';
insert into public.performances(swimmer_id,swimmer_name,course,event,seconds) select id,name,'短池','100仰',85.04 from public.swimmers where name='尹亮允';
insert into public.performances(swimmer_id,swimmer_name,course,event,seconds) select id,name,'短池','100混',85.76 from public.swimmers where name='尹亮允';
insert into public.performances(swimmer_id,swimmer_name,course,event,seconds) select id,name,'短池','50蛙',51.88 from public.swimmers where name='楊鎧銓';
insert into public.performances(swimmer_id,swimmer_name,course,event,seconds) select id,name,'短池','100蝶',86.8 from public.swimmers where name='楊鎧銓';
insert into public.performances(swimmer_id,swimmer_name,course,event,seconds) select id,name,'短池','100混',93.88 from public.swimmers where name='楊鎧銓';
insert into public.performances(swimmer_id,swimmer_name,course,event,seconds) select id,name,'短池','50仰',48.96 from public.swimmers where name='高珩晉';
insert into public.performances(swimmer_id,swimmer_name,course,event,seconds) select id,name,'短池','100自',91.21 from public.swimmers where name='高珩晉';
insert into public.performances(swimmer_id,swimmer_name,course,event,seconds) select id,name,'短池','100混',101.75 from public.swimmers where name='高珩晉';
insert into public.performances(swimmer_id,swimmer_name,course,event,seconds) select id,name,'短池','50仰',45.91 from public.swimmers where name='王暐蘅';
insert into public.performances(swimmer_id,swimmer_name,course,event,seconds) select id,name,'短池','50蝶',45.46 from public.swimmers where name='王暐蘅';
insert into public.performances(swimmer_id,swimmer_name,course,event,seconds) select id,name,'短池','100混',96.84 from public.swimmers where name='王暐蘅';
insert into public.performances(swimmer_id,swimmer_name,course,event,seconds) select id,name,'短池','50自',41.68 from public.swimmers where name='鄧丞勛';
insert into public.performances(swimmer_id,swimmer_name,course,event,seconds) select id,name,'短池','50仰',45.62 from public.swimmers where name='鄧丞勛';
insert into public.performances(swimmer_id,swimmer_name,course,event,seconds) select id,name,'短池','50蛙',51.78 from public.swimmers where name='鄧丞勛';
insert into public.performances(swimmer_id,swimmer_name,course,event,seconds) select id,name,'短池','50蝶',46.08 from public.swimmers where name='鄧丞勛';
insert into public.performances(swimmer_id,swimmer_name,course,event,seconds) select id,name,'短池','100混',102.04 from public.swimmers where name='鄧丞勛';
insert into public.performances(swimmer_id,swimmer_name,course,event,seconds) select id,name,'短池','50仰',49.57 from public.swimmers where name='高赫言';
insert into public.performances(swimmer_id,swimmer_name,course,event,seconds) select id,name,'短池','100混',110.14 from public.swimmers where name='高赫言';
insert into public.team_records(course,gender,event,swimmer_id,swimmer_name,seconds,meet) select '長池','男','50自',id,name,29.38,'2609 新莊主委' from public.swimmers where name='潘沅駿' on conflict(course,gender,event) do update set swimmer_id=excluded.swimmer_id,swimmer_name=excluded.swimmer_name,seconds=excluded.seconds,meet=excluded.meet,updated_at=now();
insert into public.team_records(course,gender,event,swimmer_id,swimmer_name,seconds,meet) select '長池','女','50自',id,name,31.33,'2509 泳協北A2' from public.swimmers where name='李亮樂' on conflict(course,gender,event) do update set swimmer_id=excluded.swimmer_id,swimmer_name=excluded.swimmer_name,seconds=excluded.seconds,meet=excluded.meet,updated_at=now();
insert into public.team_records(course,gender,event,swimmer_id,swimmer_name,seconds,meet) select '長池','男','50仰',id,name,34.19,'2609 新莊主委' from public.swimmers where name='潘沅駿' on conflict(course,gender,event) do update set swimmer_id=excluded.swimmer_id,swimmer_name=excluded.swimmer_name,seconds=excluded.seconds,meet=excluded.meet,updated_at=now();
insert into public.team_records(course,gender,event,swimmer_id,swimmer_name,seconds,meet) select '長池','女','50仰',id,name,36.87,'2506 全國青年' from public.swimmers where name='高語均' on conflict(course,gender,event) do update set swimmer_id=excluded.swimmer_id,swimmer_name=excluded.swimmer_name,seconds=excluded.seconds,meet=excluded.meet,updated_at=now();
insert into public.team_records(course,gender,event,swimmer_id,swimmer_name,seconds,meet) select '長池','男','50蛙',id,name,33.29,'2605 三峽春長' from public.swimmers where name='潘沅駿' on conflict(course,gender,event) do update set swimmer_id=excluded.swimmer_id,swimmer_name=excluded.swimmer_name,seconds=excluded.seconds,meet=excluded.meet,updated_at=now();
insert into public.team_records(course,gender,event,swimmer_id,swimmer_name,seconds,meet) select '長池','女','50蛙',id,name,41.84,'2610 泳協北A2' from public.swimmers where name='尹亮允' on conflict(course,gender,event) do update set swimmer_id=excluded.swimmer_id,swimmer_name=excluded.swimmer_name,seconds=excluded.seconds,meet=excluded.meet,updated_at=now();
insert into public.team_records(course,gender,event,swimmer_id,swimmer_name,seconds,meet) select '長池','男','50蝶',id,name,32.47,'2606 全國中正' from public.swimmers where name='潘沅駿' on conflict(course,gender,event) do update set swimmer_id=excluded.swimmer_id,swimmer_name=excluded.swimmer_name,seconds=excluded.seconds,meet=excluded.meet,updated_at=now();
insert into public.team_records(course,gender,event,swimmer_id,swimmer_name,seconds,meet) select '長池','女','50蝶',id,name,33.55,'2601 新北市中' from public.swimmers where name='李亮樂' on conflict(course,gender,event) do update set swimmer_id=excluded.swimmer_id,swimmer_name=excluded.swimmer_name,seconds=excluded.seconds,meet=excluded.meet,updated_at=now();
insert into public.team_records(course,gender,event,swimmer_id,swimmer_name,seconds,meet) select '長池','男','100自',id,name,63.74,'2604 三峽春長' from public.swimmers where name='潘沅駿' on conflict(course,gender,event) do update set swimmer_id=excluded.swimmer_id,swimmer_name=excluded.swimmer_name,seconds=excluded.seconds,meet=excluded.meet,updated_at=now();
insert into public.team_records(course,gender,event,swimmer_id,swimmer_name,seconds,meet) select '長池','女','100自',id,name,69.81,'2601 泳協北A1' from public.swimmers where name='李亮樂' on conflict(course,gender,event) do update set swimmer_id=excluded.swimmer_id,swimmer_name=excluded.swimmer_name,seconds=excluded.seconds,meet=excluded.meet,updated_at=now();
insert into public.team_records(course,gender,event,swimmer_id,swimmer_name,seconds,meet) select '長池','男','100仰',id,name,73.78,'2609 永和幼獅' from public.swimmers where name='潘沅駿' on conflict(course,gender,event) do update set swimmer_id=excluded.swimmer_id,swimmer_name=excluded.swimmer_name,seconds=excluded.seconds,meet=excluded.meet,updated_at=now();
insert into public.team_records(course,gender,event,swimmer_id,swimmer_name,seconds,meet) select '長池','女','100仰',id,name,79.86,'2506 全國青年' from public.swimmers where name='高語均' on conflict(course,gender,event) do update set swimmer_id=excluded.swimmer_id,swimmer_name=excluded.swimmer_name,seconds=excluded.seconds,meet=excluded.meet,updated_at=now();
insert into public.team_records(course,gender,event,swimmer_id,swimmer_name,seconds,meet) select '長池','男','100蛙',id,name,72.51,'2601 泳協北A1' from public.swimmers where name='潘沅駿' on conflict(course,gender,event) do update set swimmer_id=excluded.swimmer_id,swimmer_name=excluded.swimmer_name,seconds=excluded.seconds,meet=excluded.meet,updated_at=now();
insert into public.team_records(course,gender,event,swimmer_id,swimmer_name,seconds,meet) select '長池','女','100蛙',id,name,88.69,'2609 永和幼獅' from public.swimmers where name='尹亮允' on conflict(course,gender,event) do update set swimmer_id=excluded.swimmer_id,swimmer_name=excluded.swimmer_name,seconds=excluded.seconds,meet=excluded.meet,updated_at=now();
insert into public.team_records(course,gender,event,swimmer_id,swimmer_name,seconds,meet) select '長池','男','100蝶',id,name,70.77,'2609 永和幼獅' from public.swimmers where name='潘沅駿' on conflict(course,gender,event) do update set swimmer_id=excluded.swimmer_id,swimmer_name=excluded.swimmer_name,seconds=excluded.seconds,meet=excluded.meet,updated_at=now();
insert into public.team_records(course,gender,event,swimmer_id,swimmer_name,seconds,meet) select '長池','女','100蝶',id,name,80.65,'2610 泳協北A2' from public.swimmers where name='潘昱晴' on conflict(course,gender,event) do update set swimmer_id=excluded.swimmer_id,swimmer_name=excluded.swimmer_name,seconds=excluded.seconds,meet=excluded.meet,updated_at=now();
insert into public.team_records(course,gender,event,swimmer_id,swimmer_name,seconds,meet) select '長池','男','200混',id,name,152.03,'2604 夢想春季' from public.swimmers where name='潘沅駿' on conflict(course,gender,event) do update set swimmer_id=excluded.swimmer_id,swimmer_name=excluded.swimmer_name,seconds=excluded.seconds,meet=excluded.meet,updated_at=now();
insert into public.team_records(course,gender,event,swimmer_id,swimmer_name,seconds,meet) select '長池','女','200混',id,name,167.44,'2605 新北對抗' from public.swimmers where name='潘昱晴' on conflict(course,gender,event) do update set swimmer_id=excluded.swimmer_id,swimmer_name=excluded.swimmer_name,seconds=excluded.seconds,meet=excluded.meet,updated_at=now();
insert into public.team_records(course,gender,event,swimmer_id,swimmer_name,seconds,meet) select '長池','男','200自',id,name,141.69,'2509 泳協北A2' from public.swimmers where name='潘沅駿' on conflict(course,gender,event) do update set swimmer_id=excluded.swimmer_id,swimmer_name=excluded.swimmer_name,seconds=excluded.seconds,meet=excluded.meet,updated_at=now();
insert into public.team_records(course,gender,event,swimmer_id,swimmer_name,seconds,meet) select '長池','女','200自',id,name,148.72,'2610 泳協北A2' from public.swimmers where name='潘昱晴' on conflict(course,gender,event) do update set swimmer_id=excluded.swimmer_id,swimmer_name=excluded.swimmer_name,seconds=excluded.seconds,meet=excluded.meet,updated_at=now();
insert into public.team_records(course,gender,event,swimmer_id,swimmer_name,seconds,meet) select '長池','男','200蛙',id,name,159.47,'2606 全國中正' from public.swimmers where name='潘沅駿' on conflict(course,gender,event) do update set swimmer_id=excluded.swimmer_id,swimmer_name=excluded.swimmer_name,seconds=excluded.seconds,meet=excluded.meet,updated_at=now();
insert into public.team_records(course,gender,event,swimmer_id,swimmer_name,seconds,meet) select '長池','女','200蛙',id,name,188.11,'2610 泳協北A2' from public.swimmers where name='尹亮允' on conflict(course,gender,event) do update set swimmer_id=excluded.swimmer_id,swimmer_name=excluded.swimmer_name,seconds=excluded.seconds,meet=excluded.meet,updated_at=now();
insert into public.team_records(course,gender,event,swimmer_id,swimmer_name,seconds,meet) select '長池','男','400自',id,name,315.93,'2610 泳協北A2' from public.swimmers where name='曾子瑞' on conflict(course,gender,event) do update set swimmer_id=excluded.swimmer_id,swimmer_name=excluded.swimmer_name,seconds=excluded.seconds,meet=excluded.meet,updated_at=now();
insert into public.team_records(course,gender,event,swimmer_id,swimmer_name,seconds,meet) select '長池','女','400自',id,name,324.6,'2610 泳協北A2' from public.swimmers where name='尹亮允' on conflict(course,gender,event) do update set swimmer_id=excluded.swimmer_id,swimmer_name=excluded.swimmer_name,seconds=excluded.seconds,meet=excluded.meet,updated_at=now();
insert into public.team_records(course,gender,event,swimmer_id,swimmer_name,seconds,meet) select '短池','男','50自',id,name,30.36,'2412 Xports' from public.swimmers where name='吳中暟' on conflict(course,gender,event) do update set swimmer_id=excluded.swimmer_id,swimmer_name=excluded.swimmer_name,seconds=excluded.seconds,meet=excluded.meet,updated_at=now();
insert into public.team_records(course,gender,event,swimmer_id,swimmer_name,seconds,meet) select '短池','女','50自',id,name,31.6,'2412 Xports' from public.swimmers where name='李亮樂' on conflict(course,gender,event) do update set swimmer_id=excluded.swimmer_id,swimmer_name=excluded.swimmer_name,seconds=excluded.seconds,meet=excluded.meet,updated_at=now();
insert into public.team_records(course,gender,event,swimmer_id,swimmer_name,seconds,meet) select '短池','男','50仰',id,name,37.7,'2512 Xports' from public.swimmers where name='曾子瑞' on conflict(course,gender,event) do update set swimmer_id=excluded.swimmer_id,swimmer_name=excluded.swimmer_name,seconds=excluded.seconds,meet=excluded.meet,updated_at=now();
insert into public.team_records(course,gender,event,swimmer_id,swimmer_name,seconds,meet) select '短池','女','50仰',id,name,38.5,'2412 Xports' from public.swimmers where name='高語均' on conflict(course,gender,event) do update set swimmer_id=excluded.swimmer_id,swimmer_name=excluded.swimmer_name,seconds=excluded.seconds,meet=excluded.meet,updated_at=now();
insert into public.team_records(course,gender,event,swimmer_id,swimmer_name,seconds,meet) select '短池','男','50蛙',id,name,35.81,'2412 Xports' from public.swimmers where name='潘沅駿' on conflict(course,gender,event) do update set swimmer_id=excluded.swimmer_id,swimmer_name=excluded.swimmer_name,seconds=excluded.seconds,meet=excluded.meet,updated_at=now();
insert into public.team_records(course,gender,event,swimmer_id,swimmer_name,seconds,meet) select '短池','女','50蛙',id,name,45.23,'2512 Xports' from public.swimmers where name='尹亮允' on conflict(course,gender,event) do update set swimmer_id=excluded.swimmer_id,swimmer_name=excluded.swimmer_name,seconds=excluded.seconds,meet=excluded.meet,updated_at=now();
insert into public.team_records(course,gender,event,swimmer_id,swimmer_name,seconds,meet) select '短池','男','50蝶',id,name,35.79,'2512 Xports' from public.swimmers where name='曾子瑞' on conflict(course,gender,event) do update set swimmer_id=excluded.swimmer_id,swimmer_name=excluded.swimmer_name,seconds=excluded.seconds,meet=excluded.meet,updated_at=now();
insert into public.team_records(course,gender,event,swimmer_id,swimmer_name,seconds,meet) select '短池','女','50蝶',id,name,34.81,'2412 Xports' from public.swimmers where name='李亮樂' on conflict(course,gender,event) do update set swimmer_id=excluded.swimmer_id,swimmer_name=excluded.swimmer_name,seconds=excluded.seconds,meet=excluded.meet,updated_at=now();
insert into public.team_records(course,gender,event,swimmer_id,swimmer_name,seconds,meet) select '短池','男','100自',id,name,65.81,'2412 Xports' from public.swimmers where name='吳中暟' on conflict(course,gender,event) do update set swimmer_id=excluded.swimmer_id,swimmer_name=excluded.swimmer_name,seconds=excluded.seconds,meet=excluded.meet,updated_at=now();
insert into public.team_records(course,gender,event,swimmer_id,swimmer_name,seconds,meet) select '短池','女','100自',id,name,74.28,'2412 Xports' from public.swimmers where name='高語均' on conflict(course,gender,event) do update set swimmer_id=excluded.swimmer_id,swimmer_name=excluded.swimmer_name,seconds=excluded.seconds,meet=excluded.meet,updated_at=now();
insert into public.team_records(course,gender,event,swimmer_id,swimmer_name,seconds,meet) select '短池','男','100仰',id,name,78.08,'2512 Xports' from public.swimmers where name='曾子瑞' on conflict(course,gender,event) do update set swimmer_id=excluded.swimmer_id,swimmer_name=excluded.swimmer_name,seconds=excluded.seconds,meet=excluded.meet,updated_at=now();
insert into public.team_records(course,gender,event,swimmer_id,swimmer_name,seconds,meet) select '短池','女','100仰',id,name,85.04,'2512 Xports' from public.swimmers where name='尹亮允' on conflict(course,gender,event) do update set swimmer_id=excluded.swimmer_id,swimmer_name=excluded.swimmer_name,seconds=excluded.seconds,meet=excluded.meet,updated_at=now();
insert into public.team_records(course,gender,event,swimmer_id,swimmer_name,seconds,meet) select '短池','男','100蛙',id,name,78.88,'2412 Xports' from public.swimmers where name='潘沅駿' on conflict(course,gender,event) do update set swimmer_id=excluded.swimmer_id,swimmer_name=excluded.swimmer_name,seconds=excluded.seconds,meet=excluded.meet,updated_at=now();
insert into public.team_records(course,gender,event,swimmer_id,swimmer_name,seconds,meet) select '短池','男','100蝶',id,name,81.59,'2412 Xports' from public.swimmers where name='吳中暟' on conflict(course,gender,event) do update set swimmer_id=excluded.swimmer_id,swimmer_name=excluded.swimmer_name,seconds=excluded.seconds,meet=excluded.meet,updated_at=now();
insert into public.team_records(course,gender,event,swimmer_id,swimmer_name,seconds,meet) select '短池','男','100混',id,name,78.81,'2512 Xports' from public.swimmers where name='曾子瑞' on conflict(course,gender,event) do update set swimmer_id=excluded.swimmer_id,swimmer_name=excluded.swimmer_name,seconds=excluded.seconds,meet=excluded.meet,updated_at=now();
insert into public.team_records(course,gender,event,swimmer_id,swimmer_name,seconds,meet) select '短池','女','100混',id,name,85.76,'2512 Xports' from public.swimmers where name='尹亮允' on conflict(course,gender,event) do update set swimmer_id=excluded.swimmer_id,swimmer_name=excluded.swimmer_name,seconds=excluded.seconds,meet=excluded.meet,updated_at=now();
insert into public.team_records(course,gender,event,swimmer_id,swimmer_name,seconds,meet) select '短池','男','200混',id,name,162.9,'2412 Xports' from public.swimmers where name='潘沅駿' on conflict(course,gender,event) do update set swimmer_id=excluded.swimmer_id,swimmer_name=excluded.swimmer_name,seconds=excluded.seconds,meet=excluded.meet,updated_at=now();